# Generated by Django 5.1.15 on 2026-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='endereço de e-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('role', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SECRETARIA', 'Secretaria'), ('COORDENACAO', 'Coordenação')], max_length=20, verbose_name='perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('must_change_password', models.BooleanField(default=False, help_text='Indica se o usuário é obrigado a alterar a senha no próximo acesso.', verbose_name='deve trocar senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('is_staff', models.BooleanField(default=False, verbose_name='membro da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-created_at'],
            },
        ),
    ]
