# Generated by Django 5.1.15 on 2026-09-12 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/%Y/%m/', verbose_name='arquivo')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='link externo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_publicados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='academics.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'material acadêmico',
                'verbose_name_plural': 'materiais acadêmicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
