# Generated by Django 5.1.15 on 2026-09-20 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_eventocalendario_horarioturma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7, verbose_name='tipo')),
                ('instituicao_externa', models.CharField(max_length=200, verbose_name='instituição externa')),
                ('curso_externo', models.CharField(max_length=200, verbose_name='curso na instituição externa')),
                ('data_referencia', models.DateField(verbose_name='data de referência da transferência')),
                ('documentos', models.TextField(help_text='Liste os documentos apresentados ou justifique sua dispensa. Não informe senhas ou dados desnecessários.', max_length=3000, verbose_name='registro dos documentos')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', editable=False, max_length=8, verbose_name='situação')),
                ('solicitada_em', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('analisada_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='analisada em')),
                ('justificativa', models.TextField(blank=True, editable=False, max_length=3000, verbose_name='justificativa')),
                ('chave_externa', models.CharField(blank=True, editable=False, max_length=64)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('analisada_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_analisadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='academics.curso', verbose_name='curso na instituição atual')),
                ('solicitada_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de transferência',
                'verbose_name_plural': 'solicitações de transferência',
                'ordering': ['-solicitada_em', '-pk'],
                'default_permissions': ('view',),
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['ENTRADA', 'SAIDA'])), name='transfers_tipo_valido'), models.CheckConstraint(condition=models.Q(models.Q(('analisada_em__isnull', True), ('analisada_por__isnull', True), ('justificativa', ''), ('status', 'PENDENTE')), models.Q(('analisada_em__isnull', False), ('analisada_por__isnull', False), ('status__in', ['APROVADA', 'RECUSADA']), models.Q(('justificativa', ''), _negated=True)), _connector='OR'), name='transfers_decisao_consistente'), models.CheckConstraint(condition=models.Q(models.Q(('instituicao_externa', ''), _negated=True), models.Q(('curso_externo', ''), _negated=True), models.Q(('documentos', ''), _negated=True), models.Q(('chave_externa', ''), _negated=True)), name='transfers_dados_obrigatorios'), models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('aluno', 'tipo', 'curso', 'chave_externa'), name='transfers_pendente_equivalente', violation_error_message='Já existe uma solicitação pendente equivalente para este aluno.')],
            },
        ),
    ]
