# Generated by Django 5.1.15 on 2026-08-17 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.CharField(max_length=10, verbose_name='período letivo')),
                ('horarios', models.CharField(max_length=100, verbose_name='horários')),
                ('sala', models.CharField(blank=True, max_length=30, null=True, verbose_name='sala')),
                ('vagas_maximas', models.PositiveIntegerField(verbose_name='vagas máximas')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='academics.disciplina', verbose_name='disciplina')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_ministradas', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-periodo_letivo', 'disciplina__nome'],
            },
        ),
    ]
