# Generated by Django 5.1.15 on 2026-09-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import time


def parse_horario_str_para_time(horario_str):
    intervalos = []
    if not horario_str or not horario_str.strip():
        return intervalos

    string_normalizada = horario_str.replace('/', ',').replace(';', ',')
    partes = [p.strip() for p in string_normalizada.split(',')]

    for parte in partes:
        if not parte:
            continue
        try:
            sub_parts = parte.split()
            if len(sub_parts) != 2:
                continue
            dia = sub_parts[0].upper()
            if dia not in ['SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM']:
                continue
            intervalo = sub_parts[1]
            time_parts = intervalo.split('-')
            if len(time_parts) != 2:
                continue
            inicio_str, fim_str = time_parts[0].strip(), time_parts[1].strip()
            ih_str, im_str = inicio_str.split(':')
            fh_str, fm_str = fim_str.split(':')
            
            ih, im = int(ih_str), int(im_str)
            fh, fm = int(fh_str), int(fm_str)
            
            intervalos.append({
                'dia_semana': dia,
                'hora_inicio': time(ih, im),
                'hora_fim': time(fh, fm)
            })
        except (ValueError, IndexError):
            continue
    return intervalos


def migrar_horarios_textuais_para_model(apps, schema_editor):
    Turma = apps.get_model('academics', 'Turma')
    HorarioTurma = apps.get_model('academics', 'HorarioTurma')
    
    for turma in Turma.objects.all():
        intervalos = parse_horario_str_para_time(turma.horarios)
        for val in intervalos:
            if not HorarioTurma.objects.filter(
                turma=turma,
                dia_semana=val['dia_semana'],
                hora_inicio=val['hora_inicio'],
                hora_fim=val['hora_fim']
            ).exists():
                HorarioTurma.objects.create(
                    turma=turma,
                    dia_semana=val['dia_semana'],
                    hora_inicio=val['hora_inicio'],
                    hora_fim=val['hora_fim']
                )


def desfazer_migracao_horarios(apps, schema_editor):
    Turma = apps.get_model('academics', 'Turma')
    HorarioTurma = apps.get_model('academics', 'HorarioTurma')

    for turma in Turma.objects.all():
        intervalos = parse_horario_str_para_time(turma.horarios)
        for val in intervalos:
            HorarioTurma.objects.filter(
                turma=turma,
                dia_semana=val['dia_semana'],
                hora_inicio=val['hora_inicio'],
                hora_fim=val['hora_fim']
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('PROVA', 'Prova'), ('FERIADO', 'Feriado'), ('REUNIAO', 'Reunião'), ('OUTRO', 'Outro')], default='AULA', max_length=30, verbose_name='tipo')),
                ('inicio', models.DateTimeField(verbose_name='início')),
                ('fim', models.DateTimeField(verbose_name='fim')),
                ('escopo', models.CharField(choices=[('GERAL', 'Geral'), ('CURSO', 'Curso'), ('TURMA', 'Turma'), ('PAPEL', 'Papel')], default='GERAL', max_length=15, verbose_name='escopo')),
                ('papel_destino', models.CharField(blank=True, choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SECRETARIA', 'Secretaria'), ('COORDENACAO', 'Coordenação')], max_length=15, null=True, verbose_name='papel de destino')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.curso', verbose_name='curso')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'evento do calendário',
                'verbose_name_plural': 'eventos do calendário',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, verbose_name='dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('hora_fim', models.TimeField(verbose_name='hora de fim')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='academics.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'horário de aula',
                'verbose_name_plural': 'horários de aula',
                'ordering': ['dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'dia_semana', 'hora_inicio', 'hora_fim'), name='unique_horario_turma')],
            },
        ),
        migrations.RunPython(
            code=migrar_horarios_textuais_para_model,
            reverse_code=desfazer_migracao_horarios,
        ),
    ]

