# Generated by Django 5.1.15 on 2026-09-12 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('escopo', models.CharField(choices=[('GERAL', 'Geral (Todos)'), ('PAPEL', 'Por Perfil'), ('CURSO', 'Por Curso'), ('TURMA', 'Por Turma')], default='GERAL', max_length=20, verbose_name='escopo')),
                ('papel_destino', models.CharField(blank=True, choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SECRETARIA', 'Secretaria'), ('COORDENACAO', 'Coordenação')], max_length=20, null=True, verbose_name='perfil de destino')),
                ('publicar_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicar em')),
                ('expirar_em', models.DateTimeField(blank=True, null=True, verbose_name='expirar em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='academics.curso', verbose_name='curso')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='academics.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-publicar_em', '-criado_em'],
            },
        ),
    ]
