# Generated by Django 5.1.15 on 2026-09-12 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='publicar_em',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='publicar em'),
        ),
    ]
