# Generated by Django 5.1.15 on 2026-08-30 06:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_active_enrollment_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('TRABALHO', 'Trabalho'), ('EXAME', 'Exame Final')], max_length=10, verbose_name='tipo de avaliação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='nota')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='enrollment.matricula', verbose_name='matrícula')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['matricula_id', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('matricula', 'tipo'), name='unique_nota_por_matricula_tipo'), models.CheckConstraint(condition=models.Q(('valor__gte', 0), ('valor__lte', 10)), name='nota_entre_zero_e_dez')],
            },
        ),
    ]
