# Generated by Django 5.1.15 on 2026-10-08 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0002_alter_comunicado_publicar_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('COMUNICADO', 'Comunicado'), ('NOTA', 'Nota'), ('FREQUENCIA', 'Frequência')], max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.comunicado')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em', '-pk'],
                'indexes': [models.Index(fields=['destinatario', 'lida_em', '-criada_em'], name='notif_usuario_leitura_idx')],
                'constraints': [models.UniqueConstraint(fields=('destinatario', 'comunicado'), name='notificacao_comunicado_destinatario_unico')],
            },
        ),
    ]
